# Generated by Django 5.2.8 on 2025-12-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0002_alter_listing_photo_main_alter_realtor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
