# Generated by Django 5.2.8 on 2025-12-24 06:36

import page1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0004_alter_listing_bathrooms_alter_listing_realtor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to=page1.models.property_image_upload_path),
        ),
    ]
