# Generated by Django 5.2.8 on 2025-12-24 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0005_listing_latitude_listing_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='longitude',
        ),
    ]
